name: splicing-pipelines-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.9
  - trimmomatic=0.39
  - star=2.6.1d
  - samtools=1.10
  - deeptools=3.4.0
  - stringtie=2.1.1
  - multiqc=1.8