name: splicing-pipelines-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.9
  - trimmomatic=0.39
  - star=2.7.9a
  - samtools=1.13
  - deeptools=3.5.1
  - multiqc=1.11
  - bioconductor-rtracklayer=1.52.0

# Now installed via executable in `Dockerfile`
  # - stringtie=2.1.7
  # - gffread=0.12.7 (version not available on conda)
  # - gffcompare=0.12.6